version: '3.9'
services:
  desko-db:
    image: mysql:8.0
    container_name: desko-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    expose:
      - '3306'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - 'mysql-db:/var/lib/mysql'
    networks:
      - app-network
  desko-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: desko-phpmyadmin
    restart: always
    expose:
      - '80'
    ports:
      - '${PHPMYADMIN_PORT}:80'
    depends_on:
      - desko-db
    environment:
      PMA_HOST: desko-db
      PMA_PORT: '${DB_PORT}'
      PMA_ARBITRARY: 1
    networks:
      - app-network
  desko-redis:
    image: redis
    container_name: desko-redis
    expose:
      - '6379'
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - app-network
  desko-api:
    container_name: desko-api
    build:
      context: ./
      dockerfile: packages/api/Dockerfile.api
    restart: unless-stopped
    environment:
      DB_HOST: 'desko-db'
      REDIS_URL: 'desko-redis'
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - desko-db
      - desko-redis
    networks:
      - app-network
  desko-web:
    container_name: desko-web
    build:
      context: ./
      dockerfile: packages/web/Dockerfile.web
    ports:
      - '3000:3000'
    networks:
      - app-network
volumes:
  mysql-db:
networks:
  app-network:
