version: '3.9'
services:
  desko-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    expose:
      - '3306'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - 'mysql-db:/var/lib/mysql'
    networks:
      - backend-network
  desko-api:
    build:
      context: ./
      dockerfile: packages/api/Dockerfile.api
    restart: unless-stopped
    environment:
      REDIS_HOST: 'desko-redis://cache'
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - desko-db
      - desko-redis
    networks:
      - backend-network
  desko-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    expose:
      - '80'
    ports:
      - '${PHPMYADMIN_PORT}:80'
    depends_on:
      - desko-db
    environment:
      PMA_HOST: desko-db
      PMA_PORT: '${DB_PORT}'
      PMA_ARBITRARY: 1
    networks:
      - backend-network
  desko-redis:
    image: redis
    container_name: cache
    expose:
      - '6379'
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - backend-network
volumes:
  mysql-db:
networks:
  backend-network:
    driver: bridge
