version: '3.9'
services:
  # desko-db:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_DATABASE: '${DB_DATABASE}'
  #     # MYSQL_USER: '${DB_USERNAME}'
  #     # MYSQL_PASSWORD: '${DB_PASSWORD}'
  #   expose:
  #     - '3306'
  #   ports:
  #     - '${DB_PORT}:3306'
  #   volumes:
  #     - 'mysql-db:/var/lib/mysql'
  #   networks:
  #     - backend-network
  # desko-phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   expose:
  #     - '80'
  #   ports:
  #     - '${PHPMYADMIN_PORT}:80'
  #   depends_on:
  #     - desko-db
  #   environment:
  #     PMA_HOST: desko-db
  #     PMA_PORT: '${DB_PORT}'
  #     PMA_ARBITRARY: 1
  #   networks:
  #     - backend-network
  # desko-redis:
  #   image: redis
  #   container_name: cache
  #   expose:
  #     - '6379'
  #   ports:
  #     - '${REDIS_PORT}:6379'
  #   networks:
  #     - backend-network
  # desko-api:
  #   build:
  #     context: ./
  #     dockerfile: packages/api/Dockerfile.api
  #   restart: always
  #   environment:
  #     REDIS_URL: 'desko-redis://cache'
  #   ports:
  #     - '${API_PORT}:${API_PORT}'
  #   depends_on:
  #     - desko-db
  #     - desko-redis
  #   networks:
  #     - backend-network
  desko-web:
    build:
      context: ./
      dockerfile: packages/web/Dockerfile.web
    ports:
      - '3000:3000'
volumes:
  mysql-db:
networks:
  backend-network:
    driver: bridge
